### ISSUE TITLE
Implement GitHub Actions for CI/CD

### ISSUE THREAD

**Issue by oxr463** [infinite-omicron/pii-redactor#4]
- [x] shellcheck
- [ ] shunit2

**Comment by oxr463** [comment]
I would recommend creating a fake project to test out your changes, like this:

- https://github.com/oxr463/github-actions-playground

**Comment by outzhu** [comment]
Having trouble understanding how to setup shellcheck & shunit2 via Actions.

do I need to Fork them and add workflow ymls and then on pii-redactor add a workflow that calls the two workflows from the another Repositories?

**Comment by oxr463** [comment]
> Having trouble understanding how to setup shellcheck & shunit2 via Actions.
> 
> do I need to Fork them and add workflow ymls and then on pii-redactor add a workflow that calls the two workflows from the another Repositories?

First, we need to install them: (See: https://github.com/proot-me/proot/blob/master/.github/workflows/ubuntu.yml#L22).

Once they are installed, then we can run them, (See: https://github.com/oxr463/github-actions-playground/blob/master/.github/workflows/blank.yml#L27).

Since we don't have any unit tests yet, we really just need to focus on running shellcheck on `pii_redactor.sh`.

**Comment by outzhu** [comment]
[example.txt](https://github.com/infinite-omicron/pii-redactor/files/7280491/example.txt)
like this?

**Comment by oxr463** [comment]
> [example.txt](https://github.com/infinite-omicron/pii-redactor/files/7280491/example.txt) like this?

Try it and see what it does!

One hint, make sure to add `-y` after `apt install` so that it automatically accepts and doesn't hang until the job times out.

**Comment by outzhu** [comment]
![successful SC failed](https://user-images.githubusercontent.com/89468347/135909426-d19b76ff-0839-4702-9eb6-5f09eb6d81ac.png)
![SC success no errors](https://user-images.githubusercontent.com/89468347/135909984-6038e446-38c7-4517-b957-da12ba4ea09c.png)

yay

**Comment by oxr463** [comment]
We'll need to write some unit tests before we can enable GitHub Actions to run our test suite. We're good with shellcheck for now.
