### ISSUE TITLE
Implement command line arguments

### ISSUE THREAD

**Issue by oxr463** [infinite-omicron/pii-redactor#6]
Arguments:
- [x] Help
- [x] Debug
- [x] Verbose
- [x] Version

See: https://gitlab.com/oxr463/check-generator/-/blob/master/src/generator.sh#L14

**Comment by outzhu** [comment]
figured I can close this

**Comment by oxr463** [comment]
> figured I can close this

Let's close it after the PR is merged, https://github.com/infinite-omicron/pii-redactor/pull/7.

If that is ready for a review, we can take it out of Draft and I can review it.
